[package]
name = "soft-aes"
version = "0.2.2"
edition = "2021"
authors = ["David Schmid <david.schmid@mailbox.org>"]
description = "A Rust-based software library for AES."
repository = "https://github.com/5n00py/soft-aes"
license = "GPL-3.0"

[dev-dependencies]
hex = "0.4.3"
